version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.7-stretch
        steps:
            - checkout

            - restore_cache:
                key: v1-dependencies-{{ checksum "requirements.txt" }}
            - run:
                name: install depencies
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt
            - save_cache:
                key: v1-dependencies-{{ checksum "requirements.txt" }}
                paths:
                    - ".venv"

            - run:
                name: convert ipynb into py
                command: |
                    . venv/bin/activate
                    jupyter nbconvert *.ipynb --to script
            
            # - run:
            #     name: run lint
            #     command: |
            #         . venv/bin/activate
            #         pylint *.py

            - run:
                name: radon
                command: |
                    . venv/bin/activate
                    radon cc *.py -s --total-average
            
            

