version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.7-stretch
        steps:
            - checkout

            # - run: sudo chown -R circleci:circleci /usr/local/bin
            # - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
            # - restore_cache:
                # key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - run:
                name: install depencies
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt
            # - save_cache:
                # key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
                # paths:
                    # - ".venv"
                    # - "/usr/local/bin"
                    # - "/usr/local/lib/python3.7/site-packages"

            - run:
                name: convert ipynb into py
                command: |
                    . venv/bin/activate
                    jupyter nbconvert *.ipynb --to script
            
            # - run:
            #     name: run lint
            #     command: |
            #         . venv/bin/activate
            #         pylint *.py

            - run:
                name: radon
                command: |
                    . venv/bin/activate
                    radon cc *.py -s --total-average
            
            

