version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.7-stretch
              environment:
                PIPENV_VENV_IN_PROJECT: true
        steps:
            - checkout
            - run:
                name: init submodule
                command: |
                    cd tests/shared-oracles
                    git submodule update --init
                    cd shared-oracles
                    git checkout master
                    cd ../../
                    ls -R
            - run: sudo chown -R circleci:circleci /usr/local/bin
            - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages

            - restore_cache:
                key: v1-dependencies-{{ checksum "requirements.txt" }}
            - run:
                name: install pipenv
                command: |
                    sudo pip install pipenv
                    pipenv install
            - run:
                name: install depencies
                command: |
                    pipenv run pip install -r requirements.txt
            - save_cache:
                key: v1-dependencies-{{ checksum "requirements.txt" }}
                paths:
                    - ".venv"
                    - "/usr/local/bin"
                    - "/usr/local/lib/python3.7/site-packages"

            - run:
                name: convert ipynb into py
                command: |
                    cd trajectories_error
                    pipenv run jupyter nbconvert estimator.ipynb --to python
            
            # - run:
            #     name: run lint
            #     command: |
            #         pipenv run pylint *.py

            - run:
                name: radon
                command: |
                    pipenv run radon cc */*.py -s --total-average

            - run:
                name: doctest
                command: |
                    pipenv run python -m doctest trajectories_error/*.py
                    pipenv run python -m doctest tests/*.py
            
            - run:
                name: test Oracles
                command: |
                    ls
                    pipenv run python -m unittest tests.test_estimator
