version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.7-stretch
              environment:
                PIPENV_VENV_IN_PROJECT: true
        steps:
            - checkout

            - restore_cache:
                key: v1-dependencies-{{ checksum "requirements.txt" }}
            - run:
                command: |
                    sudo pip install pipenv
                    pipenv install
            - run:
                name: install depencies
                command: |
                    # python3 -m venv venv
                    # . venv/bin/activate
                    pipenv run pip install -r requirements.txt
            - save_cache:
                key: v1-dependencies-{{ checksum "requirements.txt" }}
                paths:
                    - ".venv"

            - run:
                name: convert ipynb into py
                command: |
                    # . venv/bin/activate
                    pipenv run jupyter nbconvert *.ipynb --to script
            
            # - run:
            #     name: run lint
            #     command: |
            #         . venv/bin/activate
            #         pylint *.py

            - run:
                name: radon
                command: |
                    # . venv/bin/activate
                    pipenv run radon cc *.py -s --total-average
            
            

